export interface LanguageConfig {
  id: string;
  name: string;
  nativeName: string;
  greeting: string;
  headline: string; // Full translated phrase: "learn Spanish." -> "aprende español."
  subheadline: string; // Full translated phrase: "Live it." -> "Vívelo."
  cta: string; // "Start Speaking"
  pricing_title: string; // "Invest in your fluency"
  flag: string;
  color: string; // Main theme color (hex)
  from: string; // Gradient start (hex)
  via: string; // Gradient middle (hex)
  to: string; // Gradient end (hex)
  chat_user: string;
  chat_ai: string;
  chat_explanation: string;
  students_count: string;
}

export const demoLanguages: LanguageConfig[] = [
  {
    id: "es",
    name: "Spanish",
    nativeName: "Español",
    greeting: "Hola",
    headline: "aprende español.",
    subheadline: "Vívelo.",
    cta: "Empieza a hablar",
    pricing_title: "Invierte en tu fluidez.",
    flag: "🇪🇸",
    color: "#FF0080",
    from: "#FF0080",
    via: "#FF8C00",
    to: "#7B61FF",
    chat_user: "Puedo tener la cuenta, por favor?",
    chat_ai: "¿Me traes",
    chat_explanation: "'Puedo tener' is a literal translation. 'Me traes' (Bring me) is more natural.",
    students_count: "10,000+",
  },
  {
    id: "de",
    name: "German",
    nativeName: "Deutsch",
    greeting: "Hallo",
    headline: "lerne Deutsch.",
    subheadline: "Erlebe es.",
    cta: "Fang an zu sprechen",
    pricing_title: "Investiere in deine Geläufigkeit.",
    flag: "🇩🇪",
    color: "#FFD700",
    from: "#FFD700",
    via: "#DD0000",
    to: "#000000",
    chat_user: "Kann ich haben das Menü?",
    chat_ai: "Die Speisekarte, bitte",
    chat_explanation: "In German, 'Kann ich haben' is clunky. Simply asking for the menu with 'bitte' is standard.",
    students_count: "8,500+",
  },
  {
    id: "en",
    name: "English",
    nativeName: "English",
    greeting: "Hello",
    headline: "learn English.",
    subheadline: "Live it.",
    cta: "Start Speaking",
    pricing_title: "Invest in your fluency.",
    flag: "🇬🇧",
    color: "#00247D",
    from: "#00247D",
    via: "#CF142B",
    to: "#FFFFFF",
    chat_user: "I am having 25 years old.",
    chat_ai: "I am 25",
    chat_explanation: "In English, we use 'to be' for age, not 'to have'.",
    students_count: "25,000+",
  },
  {
    id: "zh",
    name: "Chinese",
    nativeName: "中文",
    greeting: "你好",
    headline: "学好中文。",
    subheadline: "活学活用",
    cta: "开始说",
    pricing_title: "投资你的流利度",
    flag: "🇨🇳",
    color: "#DE2910",
    from: "#DE2910",
    via: "#FFDE00",
    to: "#DE2910",
    chat_user: "你叫什么?",
    chat_ai: "你贵姓?",
    chat_explanation: "'你叫什么' can be blunt. '你贵姓' is a more polite way to ask for a name.",
    students_count: "15,000+",
  },
  {
    id: "ja",
    name: "Japanese",
    nativeName: "日本語",
    greeting: "こんにちは",
    headline: "日本語を学ぼう。",
    subheadline: "体験しよう",
    cta: "話し始めよう",
    pricing_title: "流暢さへの投資",
    flag: "🇯🇵",
    color: "#BC002D",
    from: "#BC002D",
    via: "#FFFFFF",
    to: "#BC002D",
    chat_user: "これ を 食べたい です。",
    chat_ai: "これ を お願いします。",
    chat_explanation: "While 'tabetai' is correct, 'onegaishimasu' is much more common when ordering.",
    students_count: "12,000+",
  },
  {
    id: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    greeting: "नमस्ते",
    headline: "हिन्दी सीखें।",
    subheadline: "इसे जियो",
    cta: "बोलना शुरू करें",
    pricing_title: "अपने प्रवाह में निवेश करें",
    flag: "🇮🇳",
    color: "#FF9933",
    from: "#FF9933",
    via: "#FFFFFF",
    to: "#138808",
    chat_user: "क्या हाल है?",
    chat_ai: "आप कैसे हैं?",
    chat_explanation: "'क्या हाल है' is very casual. 'आप कैसे हैं' is better for formal situations.",
    students_count: "18,000+",
  },
  {
    id: "yue",
    name: "Cantonese",
    nativeName: "粵語",
    greeting: "你好",
    headline: "學好廣東話。",
    subheadline: "活學活用",
    cta: "開始講",
    pricing_title: "投資你嘅流利度",
    flag: "🇭🇰",
    color: "#C8102E",
    from: "#C8102E",
    via: "#FFFFFF",
    to: "#C8102E",
    chat_user: "唔該, 俾個單我。",
    chat_ai: "埋單, 唔該。",
    chat_explanation: "'埋單' is the standard term for 'the bill' in Hong Kong restaurants.",
    students_count: "5,000+",
  },
  {
    id: "fr",
    name: "French",
    nativeName: "Français",
    greeting: "Bonjour",
    headline: "apprenez le français.",
    subheadline: "Vivez-le.",
    cta: "Commencez à parler",
    pricing_title: "Investissez dans votre fluidité.",
    flag: "🇫🇷",
    color: "#0055A4",
    from: "#0055A4",
    via: "#FFFFFF",
    to: "#EF4135",
    chat_user: "Je suis fini.",
    chat_ai: "J'ai fini",
    chat_explanation: "Careful! 'Je suis fini' means 'I am dead/doomed'. Use 'J'ai fini' for 'I'm done'.",
    students_count: "14,000+",
  },
  {
    id: "it",
    name: "Italian",
    nativeName: "Italiano",
    greeting: "Ciao",
    headline: "impara l'italiano.",
    subheadline: "Vivilo.",
    cta: "Inizia a parlare",
    pricing_title: "Investi nella tua fluidità.",
    flag: "🇮🇹",
    color: "#009246",
    from: "#009246",
    via: "#FFFFFF",
    to: "#CE2B37",
    chat_user: "Io voglio una pizza.",
    chat_ai: "Vorrei una pizza",
    chat_explanation: "'Voglio' is too demanding. 'Vorrei' (I would like) is much more polite.",
    students_count: "9,000+",
  },
  {
    id: "pt",
    name: "Portuguese",
    nativeName: "Português",
    greeting: "Olá",
    headline: "aprenda português.",
    subheadline: "Viva isso.",
    cta: "Comece a falar",
    pricing_title: "Invista na sua fluência.",
    flag: "🇵🇹",
    color: "#046A38",
    from: "#046A38",
    via: "#DA291C",
    to: "#FFD100",
    chat_user: "Tudo bem com você?",
    chat_ai: "E aí, beleza?",
    chat_explanation: "In Brazil, 'E aí, beleza?' is a super common and natural way to greet friends.",
    students_count: "7,000+",
  },
  {
    id: "ar",
    name: "Arabic",
    nativeName: "العربية",
    greeting: "مرحبا",
    headline: "تعلم العربية.",
    subheadline: "عشها.",
    cta: "ابدأ التحدث",
    pricing_title: "استثمر في طلاقتك.",
    flag: "🇸🇦",
    color: "#006C35",
    from: "#006C35",
    via: "#FFFFFF",
    to: "#000000",
    chat_user: "أنا أحب السفر.",
    chat_ai: "بدي أسافر",
    chat_explanation: "'أنا أحب' is Modern Standard. In Levantine dialect, 'بدي' is used for 'I want'.",
    students_count: "11,000+",
  },
  {
    id: "ru",
    name: "Russian",
    nativeName: "Русский",
    greeting: "Привет",
    headline: "учи русский.",
    subheadline: "Живи этим.",
    cta: "Начни говорить",
    pricing_title: "Инвестируй в свою беглость.",
    flag: "🇷🇺",
    color: "#0039A6",
    from: "#FFFFFF",
    via: "#0039A6",
    to: "#D52B1E",
    chat_user: "Как вы имеете себя?",
    chat_ai: "Как дела?",
    chat_explanation: "Don't translate 'How are you' literally. 'Как дела?' is the correct idiom.",
    students_count: "6,000+",
  },
  {
    id: "ko",
    name: "Korean",
    nativeName: "한국어",
    greeting: "안녕하세요",
    headline: "한국어를 배워보세요.",
    subheadline: "살아보세요.",
    cta: "말하기 시작하세요",
    pricing_title: "유창함에 투자하세요.",
    flag: "🇰🇷",
    color: "#0047A0",
    from: "#CD2E3A",
    via: "#0047A0",
    to: "#000000",
    chat_user: "밥을 먹었어?",
    chat_ai: "식사하셨어요?",
    chat_explanation: "When speaking to someone older, use the honorific '식사하셨어요?' instead of casual.",
    students_count: "13,000+",
  },
  {
    id: "ur",
    name: "Urdu",
    nativeName: "اردو",
    greeting: "السلام علیکم",
    headline: "اردو سیکھیں۔",
    subheadline: "اسے جیو۔",
    cta: "بولنا شروع کریں",
    pricing_title: "अपनी रोानी में سرمایہ کاری کریں۔",
    flag: "🇵🇰",
    color: "#00401A",
    from: "#00401A",
    via: "#FFFFFF",
    to: "#00401A",
    chat_user: "آپ کا نام کیا ہے؟",
    chat_ai: "آپ کا اسمِ گرامی؟",
    chat_explanation: "In formal Urdu, 'اسمِ گرامی' is a very respectful way to ask for a name.",
    students_count: "4,000+",
  },
  {
    id: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    greeting: "வணக்கம்",
    headline: "தமிழ் கற்கவும்.",
    subheadline: "அதை வாழுங்கள்.",
    cta: "பேசத் தொடங்குங்கள்",
    pricing_title: "உங்கள் புலமையில் முதலீடு செய்யுங்கள்.",
    flag: "🇱🇰",
    color: "#8D153A",
    from: "#8D153A",
    via: "#FF7F00",
    to: "#005236",
    chat_user: "சாப்டியா?",
    chat_ai: "சாப்பிட்டீர்களா?",
    chat_explanation: "'சாப்டியா?' is very colloquial. 'சாப்பிட்டீர்களா?' is polite and standard.",
    students_count: "3,500+",
  },
  {
    id: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    greeting: "হ্যালো",
    headline: "বাংলা শিখুন।",
    subheadline: "এটা বাচো.",
    cta: "কথা বলা শুরু করুন",
    pricing_title: "আপনার সাবলীলতায় বিনিয়োগ করুন।",
    flag: "🇧🇩",
    color: "#006A4E",
    from: "#006A4E",
    via: "#F42A41",
    to: "#006A4E",
    chat_user: "কেমন আছো?",
    chat_ai: "কেমন আছেন?",
    chat_explanation: "Use 'আছেন' for elders or in formal settings to show respect.",
    students_count: "4,500+",
  },
  {
    id: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    greeting: "Hej",
    headline: "lär dig svenska.",
    subheadline: "Lev det.",
    cta: "Börja prata",
    pricing_title: "Investera i ditt flyt.",
    flag: "🇸🇪",
    color: "#006AA7",
    from: "#006AA7",
    via: "#FECC00",
    to: "#006AA7",
    chat_user: "Kan jag ha en kaffe?",
    chat_ai: "Jag tar en kaffe, tack",
    chat_explanation: "Swedes often use 'Jag tar' (I take) when ordering in a cafe.",
    students_count: "2,500+",
  },
  {
    id: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    greeting: "Xin chào",
    headline: "học tiếng Việt.",
    subheadline: "Sống với nó.",
    cta: "Bắt đầu nói",
    pricing_title: "Đầu tư vào sự lưu loát của bạn.",
    flag: "🇻🇳",
    color: "#DA251D",
    from: "#DA251D",
    via: "#FFFF00",
    to: "#DA251D",
    chat_user: "Bạn khỏe không?",
    chat_ai: "Dạo này sao rồi?",
    chat_explanation: "'Bạn khỏe không?' is literal. 'Dạo này sao rồi?' is a more natural 'How's it going?'.",
    students_count: "4,200+",
  },
  {
    id: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    greeting: "Hujambo",
    headline: "jifunze Kiswahili.",
    subheadline: "Ishi.",
    cta: "Anza Kuzungumza",
    pricing_title: "Wekeza katika ufasaha wako.",
    flag: "🇰🇪",
    color: "#000000",
    from: "#000000",
    via: "#BB0000",
    to: "#006600",
    chat_user: "Habari gani?",
    chat_ai: "Mambo vipi?",
    chat_explanation: "'Mambo vipi?' is very common street slang in Nairobi or Dar es Salaam.",
    students_count: "3,100+",
  },
  {
    id: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    greeting: "Halo",
    headline: "belajar bahasa Indonesia.",
    subheadline: "Jalanilah.",
    cta: "Mulai Bicara",
    pricing_title: "Investasikan kefasihan Anda.",
    flag: "🇮🇩",
    color: "#FF0000",
    from: "#FF0000",
    via: "#FFFFFF",
    to: "#FF0000",
    chat_user: "Bisa saya pesan makanan?",
    chat_ai: "Mau pesan dong",
    chat_explanation: "'Mau pesan dong' is a friendly, natural way to signal you're ready to order.",
    students_count: "3,800+",
  }
];
